import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PizzaWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [toggleMenu, setToggleMenu] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
