import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import MenuBar from "@/components/MenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PizzaWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuBar />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
